language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_workspace: Project/TripKit.xcworkspace
xcode_scheme:
    - TripKit
podfile: Project/Podfile

before_install:
- echo -e "machine github.com\n  login SkedGoTravis\n  password $CI_USER_PASSWORD" >> ~/.netrc